### ISSUE TITLE
midv2019 support

### ISSUE THREAD

**Issue by fcakyon** [fcakyon/midv500#1]
I really like what you have done on your fork @AlexLi0605. If you would like to send your updates as a pull request, I would gladly accept it and publish it as a new version :+1:

**Comment by AlexLi0605** [comment]
@fcakyon 
No problem, I'll send a PR after I clean up the code first!

**Comment by fcakyon** [comment]
@AlexLi0605 Good to hear that, take your time!

**Comment by fcakyon** [comment]
midv-2019 support has been [comitted](https://github.com/fcakyon/midv500/commit/3f766d0530e896f5f38c54e95b6fbf73c5025f83#r41590126) to the master, will be published in the following package release ( 0.2.0)
